### ISSUE TITLE
small bug in example on website

### ISSUE THREAD

**Issue by m-royer** [darsain/sly#146]
On the example website after deleting all the slides, and then adding two more (so there are a total of two after previously being 0), the next button does not become active until you click on another slide. It seems to act as if it is still at the end of the list even though more have been added. 
A similar thing happens when you scroll all the way left, delete all the slides, and add more. The next button stays active, even though there are no more slides.

**Comment by darsain** [comment]
This should be fixed by aa4e8942b751de891fa4b66ea17f7d273c9b58aa.
