### ISSUE TITLE
Stop Scrolling on jQuery UI Sotable

### ISSUE THREAD

**Issue by ediboy** [darsain/sly#162]
Hi,

How can I pause/stop the scrolling when I'm currently dragging an element using jQuery UI sortable. 

Thanks in advanced,

**Comment by darsain** [comment]
Don't enable dragging.

**Comment by ediboy** [comment]
I need the dragging to be enabled and scrolling to be disabled.

**Comment by darsain** [comment]
Than disable scrolling? But scrolling doesn't happen when you drag, so I don't really understand the problem.
