### ISSUE TITLE
startAt broken as of 1.3.0

### ISSUE THREAD

**Issue by notacouch** [darsain/sly#165]
Right before calling the `load` function in `init`, `self.initialized` is flagged as true. This prevents the application of the `startAt` option.

Since all I needed was a quick fix, for now I just gave `load` a single boolean argument to determine if it was being called by `init` or not and added that condition, example here:
https://github.com/notacouch/sly/commit/86cd8ca89aad02a7e4392896431e2bcee04861f9

(looking at it now... taking out the comments at the beginning was unintentional, not sure where I was copy/pasting from that I managed to do that.)

**Comment by discotizer** [comment]
Can confirm that... see your example "Just goofin around..." Active slide should be no. 3 instead of no. 1.

**Comment by darsain** [comment]
I'll look into it when I'll have some time. Hopefully this week.

**Comment by hastoukopsaro** [comment]
I would also like this fixed. Thanks for your efforts :+1:
