### ISSUE TITLE
keyboard navigation stops working on all sly instances if only one is destroyed

### ISSUE THREAD

**Issue by flexphperia** [darsain/sly#166]
When we have more than one instances of Sly and one of it's is destroyed, ```destroy``` method will ``` unbind``` ```keyboardHandler``` function from ```$doc``` element like this:
```$doc.unbind('.' + namespace);```

This will remove ```keyboardHandler``` function from all instances of sly even those that are not the part of ```destroy``` call.

**Comment by darsain** [comment]
Tru. I'll fix it when I'll have some time.
