### ISSUE TITLE
How can I make iframe draggable?

### ISSUE THREAD

**Issue by hanj99** [darsain/sly#173]
I'm using a sly horizontal scrolling with a satisfaction :)

But, when I'm mixing images with iframe( which is used to play youtube video ), I can't drag horizontally on the video area. Is there any way I can get scrolling?

```
<div id="sly_container" class="frame">
  <ul class="slidee list_screenshot">
   <li>
     <iframe src="http://youtube.com/xxx" frameborder="0"></iframe>  // not draggable here
   </li>
   <li>
      <img src="source_url"/>  // draggable
   </li>
  </ul>
</div>
```

**Comment by darsain** [comment]
Closing as a duplicate of #174.
