### ISSUE TITLE
How can I make iframe draggable?

### ISSUE THREAD

**Issue by hanj99** [darsain/sly#174]
I'm using a sly horizontal scrolling with a satisfaction :)

But, when I'm mixing images with iframe( which is used to play youtube video ), I can't drag horizontally on the video area. Is there any way I can get scrolling?

```
<div id="sly_container" class="frame">
    <ul class="slidee list_screenshot">
       <li>
          <iframe src="http://youtube.com/xxx" frameborder="0"></iframe>  // not draggable here
       </li>
       <li>
          <img src="source_url"/>  // draggable
       </li>
       <li>
           ....
       </li>
     </ul>
</div>
```

**Comment by darsain** [comment]
You can't. All the mouse events triggered in an iframe are kept inside an iframe. You'd need a non-trivial events passing implementation to make it work.

**Comment by hanj99** [comment]
Thank you for your reply. I would have to change video area with a screenshot and inject a link on it.
