### ISSUE TITLE
Keyboard navigation controls multiple galleries instead of one

### ISSUE THREAD

**Issue by notacouch** [darsain/sly#179]
I have 2 galleries with the `keyboardNavBy: 'items'` option on the same page, navigating one via keyboard navigates the other and vice versa.

**Comment by darsain** [comment]
Than don't enable keyboard navigation for both galleries. Sly does what you tell him to do.

`keyboardNavBy` is a [dynamic option](https://github.com/darsain/sly/blob/master/docs/Methods.md#setname-value), so you can do `.set('keyboardNavBy', whatever)` without re-creating Sly instance.
