### ISSUE TITLE
Scroll on Mouse Move

### ISSUE THREAD

**Issue by blpraveen** [darsain/sly#180]
1)I want to know is it possible to scroll the items on mouse move instead of Mouse drag?

2)And also If items includes iframe as in my case . I am using sly to scroll widgets. Widgets includes corss domain iframes which will not allow to dispatch the mouse move event to the parent.

**Comment by darsain** [comment]
1. Yes, if you implement it using Sly's API. I suggest looking into [`.slideTo()`](https://github.com/darsain/sly/blob/master/docs/Methods.md#slidetoposition-immediate) method.

2. The same-origin-policy prevents you from listening to what is going on in the Iframe. Youd have to pass messages between iframe and parent window, and simulate events in parent. Not trivial.

**Comment by blpraveen** [comment]
Thanks , to my first point  I was trying  accelerated scroll http://alexmatchneer.com/blog/2012/11/12/jquery-accelerated-hover-scroll/.  It is working and I am using it in the slider. 
Regarding Iframe I would give up as the links are external and I could not modify the external source link
