### ISSUE TITLE
item align to offset

### ISSUE THREAD

**Issue by flexphperia** [darsain/sly#184]
It would be nice to have possibility align item to specified frame offset.
Whole auto align functionality from ```forceCentered``` item navigation type but with specifing ```offset``` option. Align to left/right or top/bottom border of item.
For example setting ```offset = 200``` when ```horizontal = true``` will align items to 200px from left border of frame.

**Comment by darsain** [comment]
Duplicate of #140

**Comment by flexphperia** [comment]
#140 is for not aligning items after sliding anim.
I'm requesting alignining to specified point with auto align functionality lkie ```forceCentered``` nav

**Comment by darsain** [comment]
That is currently unsupported and I don't see it getting implemented. It's quite an edge case.

However, the 2.0 rewrite (if I'll ever get to it) will feature a complete API overhaul with code over configuration focus, which will allow you to implement stuff like this if you wish.
