### ISSUE TITLE
Scroll on iphone or iPod to prevent Click Event

### ISSUE THREAD

**Issue by tankhit** [darsain/sly#186]
When I scroll on iPhone or iPod to prevent click event,and doesn't reinitialized scroll when update content,

any idea how to fix?

Thanks

**Comment by darsain** [comment]
I was unable to comprehend your question.

**Comment by tankhit** [comment]
1) when i swipe-scrolling vertical in iPhone or iPad to trigger click event instead of scroll 
2) content of HTML is change to doesn't update vertical scroll bar,

i have update sly.js file but, doesn't work it

how to fix ?

**Comment by darsain** [comment]
Still no idea what you're talking about. Sorry man, the language barrier seems to be too big.
