### ISSUE TITLE
Scroll with in an accordion tab

### ISSUE THREAD

**Issue by blpraveen** [darsain/sly#190]
I am using sly vertical notitembased scroll inside an accordion which is hidden initially and opens on tab click.
Nothing happens, ti  does not scroll.
Any solution please or  I need to copy more information.

Thanks
B L Praveen

**Comment by darsain** [comment]
Hidden elements don't have dimensions, thus Sly is unable to properly initialize. Either initialize or call `.reload()` when you show Sly.
