### ISSUE TITLE
mousewheel special move

### ISSUE THREAD

**Issue by fawado** [darsain/sly#191]
Hi !
First, thank you for your work, Sly is very interesting. 
Sorry for my english, i'm french.
I would like to know if it's possible to do something like this http://alvarotrigo.com/multiScroll/#first (not the "multi") but the special move when we move the mousewheel. In Sly, when I move the mousewheel a big time, it's scrool a lot, but when a i move a little my mousewheel, it move a little... "normal", but Iwould like, that, when i move my mousewheel a little or a lot in one time, that's move just to the next li.

I think i'm not very clear but i don't find all my word... sorry. 
Thanks

**Comment by darsain** [comment]
That would be a horrible scrolling experience for someone that wants to scroll quickly. Not happening.

But you can always implement it yourself using Sly API. Just don't enable scrolling, start listening for wheel events yourself, and slide when you want, where you want.
