### ISSUE TITLE
OuterWidth and OuterHeight return object

### ISSUE THREAD

**Issue by blpraveen** [darsain/sly#193]
Please check this link http://bugs.jquery.com/ticket/12491. Having this issue when  using jquery 1.9.1.

By making following changes  it seems to work as expected.
    var itemSize = $item[o.horizontal ? 'outerWidth' : 'outerHeight'](false);

**Comment by darsain** [comment]
I'm having trouble understanding what is the issue. What's happening? Can you please replicate on jsfiddle or a similar service?
