### ISSUE TITLE
mousedown event of next page button

### ISSUE THREAD

**Issue by relmxpillar** [darsain/sly#197]
Hi,

I am trying to add "activatePageOn: 'mousedown touchstart'" to getting a more responsive touch experience for the "prevPage/nextPage" button, it's not working but the navigation list (the bullets).

I am using the following to test.

Cycling by pages
http://darsa.in/sly/examples/horizontal.html

It's not support?

Many thanks.

**Comment by darsain** [comment]
The `activatePageOn` option affects only pagesBar, not navigation buttons, which work on clicks.

But you can still implement it yourself using Sly API:

```
$('.nextpage').on('mousedown', function () {
  sly.nextPage();
})
```

**Comment by relmxpillar** [comment]
Hi darsain,

It works, many thanks!
