### ISSUE TITLE
Vertical and Horizontal together!

### ISSUE THREAD

**Issue by siamakmokhtari** [darsain/sly#198]
Hey guy, I hope you are fine...
I wanna use this plugin in my project but I have a question:
My project like rubik's cube has 4 rows (horizontal mode) and 6 columns (vertical mode) my question is Can I use both at the same time I use them? (Vertical and Horizontal) If sly able to do please help me!

Thanks for watching...

**Comment by darsain** [comment]
No. Sly is for one directional scrolling. There is no way how to shoehorn a Rubik's cube into it.
