### ISSUE TITLE
How do i make it go based on li navigation buttons?

### ISSUE THREAD

**Issue by techsin** [darsain/sly#199]
I want to do something like this:
    
    <li data-item = "0">First Page</li>
    <li data-item = "1">2nd Page</li>
    <li data-item = "2">3rd Page</li>

so either one of these clicked then frame scrolls to those slides and if someone slides to one of the slides **a class gets attached to the li item**.

I have been looking in documents they seem to talk about scrollbar a lot but no where about buttons or li. However examples have something similar as in horizontal navigation examples pages.

**Comment by darsain** [comment]
You are looking for [`pagesBar`](https://github.com/darsain/sly/blob/master/docs/Options.md#pagesbar-1) (and `pageBuilder` below it) options.
