### ISSUE TITLE
Redefine Sly options on reload

### ISSUE THREAD

**Issue by lolo34140** [darsain/sly#201]
Hello,

Is there a way to redefine Sly option on reload method.
For example I init Sly with option `startAt : 3` and after I hide elements or append elements and it always (re) startAt 3. I would like to reset this option (to 0 for example) after init for futur reload method. What is the way to do that?

lolo

**Comment by darsain** [comment]
I don't understand what you mean. `startAt` is used only at start (Sly initialization), which happens only once, when you created and initialized Sly instance. When you call `reload()` the current active item doesn't change.

You can change options with [`#set()` method](https://github.com/darsain/sly/blob/master/docs/Methods.md#setname-value). The documentation on that link also lists all the options that can be changed dynamically.
