### ISSUE TITLE
vendor prefixes are case sensitive

### ISSUE THREAD

**Issue by flexphperia** [darsain/sly#202]
In line 2048 we have:
```var prefixes = ['', 'webkit', 'moz', 'ms', 'o'];```

and should be:
```var prefixes = ['', 'Webkit', 'Moz', 'ms', 'O'];```

see here for details:
http://blogs.msdn.com/b/thebeebs/archive/2012/01/11/with-vendor-prefixes-what-is-the-javascript-equivalent-of-ms.aspx

**Comment by darsain** [comment]
Thx :) Thought it was all starting with lowercase.
