### ISSUE TITLE
Destroy via proxy is not working

### ISSUE THREAD

**Issue by vedmaka** [darsain/sly#212]
I've noticed that destroying slider via proxy method is not working:
```
$("#myslider").sly(false);
```
Only direct **destroy** call works. You can try it yourself at Sly promo page:
Navigate to http://darsa.in/sly/ , open JS console and execute this code:

```
$('.frame').sly(false);
```

Nothing was destroyed.

**Comment by vedmaka** [comment]
Btw, none of methods working when called via proxy - you can test it at http://darsa.in/sly/ too. Eg:
```
$('.frame').sly('slideTo',100);
```
Do nothing.

**Comment by vedmaka** [comment]
Update: made few test and found that destroy via proxy working only if slider was initialized via proxy:
```
$('#frame').sly({ ..... })
```

**Comment by vedmaka** [comment]
Reason why this happening is that reference to Sly instance stored in data attribute only when Sly created via proxy. Pull request: #213

**Comment by darsain** [comment]
Yeah, that was kinda by design, but I guess it makes sense while Sly still supports jQuery. I'm gonna implement your fix.

And sorry for the delay :neutral_face:.

**Comment by darsain** [comment]
Should be fixed now.

**Comment by vedmaka** [comment]
Hooray, thanks! :smile_cat:
