### ISSUE TITLE
iPhone-like scroll-tick event

### ISSUE THREAD

**Issue by kluplau** [darsain/sly#215]
I was wondering if it is possible to get an event each time an item is passed?
Think of the iPhone calendar scroll-list, where it fires a tick-sound each time an item is centered.

I thought that the `cycle`-event was what I was looking for, but I guess it's not.

**Comment by darsain** [comment]
There isn't an event that does this, and I don't think I'll be adding it. Things like this are I think in a definition of feature creep :) which Sly is already very guilty of.

**But**! you can implement it with existing API.

Listen for `move` event, which fires every time a movement frame is rendered (synced with requestAnimationFrame), and inside it, check [`sly.rel`](https://github.com/darsain/sly/blob/master/docs/Properties.md#slyrel) object, which has useful properties like `firstItem` (first visible item in a frame), `lastItem` (last visible), etc.

Than just cache the index of a desired property, and fire an event when it changes.

**Comment by kluplau** [comment]
Okay, totally understand you...
Great, I will look into that... thanks! :+1:
