### ISSUE TITLE
Mouse wheel scrolling on smart mode

### ISSUE THREAD

**Issue by luscarpa** [darsain/sly#217]
Is there a way to enable scrolling on item-based navigation?

**Comment by darsain** [comment]
Scrolling does work on item based navigation. It's enabled by [scrollBy](https://github.com/darsain/sly/blob/master/docs/Options.md#scrollby) option. This option means different things for different navigation types, so make sure to actually read the docs.

**Comment by luscarpa** [comment]
I have read it, but it doesn't work, for example in your vertical demo that has scrollBy:1, the mouse scroll not works. 

http://darsa.in/sly/examples/vertical.html

**Comment by luscarpa** [comment]
I found the problem, I miss the setting "scrollTrap"
