### ISSUE TITLE
Start at the end (One item per frame)

### ISSUE THREAD

**Issue by Nycko97** [darsain/sly#222]
Hi,
I would like the last "item_year" get the class "active", not the first for start the slide from the left. How can I do this ? What could I change in the sly.js or anything else ? I try with startAt but it don't work and here on the picture there is only 3 "div" but in the future it will change so i can't put a static number.
I hope that you'll understand what I mean and sorry if my english is not correct.

Thank you

![capture d ecran 2015-10-01 a 03 44 16](https://cloud.githubusercontent.com/assets/14917274/10211018/cda8f2fe-67ee-11e5-9d93-1e70f97980c6.png)

**Comment by darsain** [comment]
I'm not 100% sure, but you can try using negative index in `startAt` option to select last item, like so:

``` js
startAt: -1
```

_Should_ work.

If it doesn't, you can still use Sly's API to do what you want. Just call toEnd after the initialization:

``` js
new Sly(frame, options).init().toEnd();
```

**Comment by Nycko97** [comment]
Thank you it's work well with "toEnd". 
An other relative question, when the page load I see the effect from the first item to the last. How can I remove this effect to show the last item without the sliding (only when I arrive at the page)

**Comment by darsain** [comment]
``` js
new Sly(frame, options).init().toEnd(true);
```

**Comment by Nycko97** [comment]
Thank you :+1: for the rapidity and the efficiency
