### ISSUE TITLE
Disable wheel scrolling

### ISSUE THREAD

**Issue by Rebnev** [darsain/sly#223]
Hello! Then I'm making responsive design, I need to create slider on mobile version, and destroy them on full version, create and destroy always on each resize. Make be "sly" has some solution to disable scrolling by wheel? And this solution can make my life better)

**Comment by darsain** [comment]
Option to disable/enable scroling by wheel is `scrollBy`. Either leave it at default `0` (disabled), or set it to be `0` with `sly.set('scrollBy', 0)`.

All Sly options and what they do is documented here: https://github.com/darsain/sly/blob/master/docs/Methods.md#setname-value

set method, along with list of all options that can be changed dynamically (after Sly initiation) is documented here: https://github.com/darsain/sly/blob/master/docs/Methods.md#setname-value
