### ISSUE TITLE
ES6 - PORT

### ISSUE THREAD

**Issue by hitmands** [darsain/sly#244]
Hi, 
is there any plan to port this plugin to ECMASCRIPT-6 ?

Should be helpful the ability to allow ES-6 imports
`import Sly from 'path/to/sly`

Thanks in advance

**Comment by rheilgm** [comment]
in the meantime you can use require to include this to your project:

```
window.jQuery = require('jquery');
require('sly-scrolling/dist/sly');
```

**Comment by p-decoraid** [comment]
I have an implementation of this in #268.

**Comment by hitmands** [comment]
is this still ongoing or should we close it?
