### ISSUE TITLE
Horizontal scrolling on Mac

### ISSUE THREAD

**Issue by XGhozt** [darsain/sly#266]
Can anyone else confirm, this doesn't seem to be working at all on a Mac. Works fine on Windows. Results are the same on any browser. Just can't seem to scroll horizontally on a Mac with a magic mouse.

**Comment by mrpritchett** [comment]
I can confirm that this works fine with a magic mouse on Mac (3 different macs with 3 different magic mice).

**Comment by XGhozt** [comment]
@mrpritchett Are you on OS 10.11.6? I have a laptop and a desktop machine on that version and neither of those machines can scroll down on the horizontal demos.

**Comment by XGhozt** [comment]
Looks like it has to do with the "scrollTrap" option, when it's set to "false" it doesn't work. When set to "true" it works fine. This is issue is only on Mac machines.

**Comment by dcdieci** [comment]
I can confirm this issue. Scrolling was not working for me in horizontal mode on a mac with mouse and mousewheel scroll.

**Comment by adamalton** [comment]
I can confirm this issue.  I'm using OS X 10.10.5, and horizontal scrolling doesn't work either with the built-in trackpad or with my Microsoft USB mouse (which supports horizontal scrolling via the scroll wheel).

Changing the `scrollTrap` option to `true` allows the horizontal scrolling to work, but then means that you can no longer scroll vertically, so it's not a viable workaround.

**Comment by adamalton** [comment]
@XGhozt00 are you able to update the title of this issue to be "Horizontal scrolling on Mac" rather than "Magic Mouse and horizontal scrolling"?  If it's clear that it affects all Mac users then it might get more attention 😀
