### ISSUE TITLE
touchDragging - horizontal Sly 'locks' vertical scrolling

### ISSUE THREAD

**Issue by bogdosarov** [darsain/sly#41]
If you pull the page for the slider up or down the page does not scroll. How to make so that the page can scroll when it is pulling the slider?

![IMG_1252](https://f.cloud.github.com/assets/1942057/328639/dfca1f26-9b9f-11e2-921b-859e7fd011aa.jpg)

**Comment by tankhit** [comment]
i have same issue regarding scroll bar, i have update latest code from src/sly.js but don't get output proper
