### ISSUE TITLE
loop

### ISSUE THREAD

**Issue by drmax24** [darsain/sly#9]
Well i'm executing this code on the left navigation arrow click to make a loop.

jQuery("#list li:first").before(jQuery("#list li:last"));

reload() function does not handle the change well (it misses the change).
Can you give me a hint?

P.S.: when i hit left arrow it should go 1 step from the ACTIVE element. But it has some different logics

**Comment by Mario-Boss** [comment]
Hello everyone.. It is old topic but I have to re-new.
I have played with the library a little more and I have found pretty much good trick to make an infinite loop. Is not perfect solution for now, but can be good base for someone who wants use it and improve. 

The same topic you can follow here: https://stackoverflow.com/questions/45479101/darsain-sly-infinite-loop-the-first-slide-should-apear-at-the-end

Please see below code:

    var $frame  = $('#smart');
    var $slidee = $frame.children('ul').eq(0);
    var $wrap   = $frame.parent();
    var $options = {
    	itemNav: 'basic',
    	smart: 1,
    	activateOn: 'click',
    	mouseDragging: 1,
    	touchDragging: 1,
    	releaseSwing: 1,
    	scrollBy: 1,
    	pagesBar: $wrap.find('.pages'),
    	activatePageOn: 'click',
    	speed: 1000,
    	elasticBounds: 1,
    	dragHandle: 1,
    	dynamicHandle: 1,
    	clickBar: 1,
    	cycleBy: 'items'
    };
    var sly = new Sly($frame, $options);
    sly.on('change',function(eventName){
    	var clone = $($slidee).find('li').first().html();
    	$($slidee).append('<li>'+ clone + '</li>');
    	$($slidee).find('li').first().remove();
    	this.slideTo(1);
    });
    
    sly.init();
